version: "3.9"

services:
  db:
    image: postgres:15
    container_name: clickai_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clickai_net

  backend:
    container_name: clickai_backend
    build: ./backend
    restart: unless-stopped
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - media_data:/app/media
      - ./backend/static:/app/static
    env_file:
      - .env.prod
    networks:
      - clickai_net
    depends_on:
      - db

  frontend:
    container_name: clickai_frontend
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - clickai_net
    depends_on:
      - backend

  gateway:
    build: ./infrastructure/gateway
    container_name: clickai_gateway
    restart: unless-stopped
    volumes:
      - ./backend/static:/app/static
      - media_data:/app/media
      - ./frontend/dist:/app/frontend/dist
    ports:
      - "80:80"
    networks:
      - clickai_net
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  media_data:


networks:
  clickai_net:
    driver: bridge
