services:
  - type: web
    name: clickai-backend
    env: docker
    plan: free
    region: singapore # or frankfurt, nearest to UAE
    rootDir: backend
    buildCommand: "./entrypoint.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
